# @package _global_
mixed_precision: "fp8"
fp8_backend: "te"
fp8_format: "HYBRID"
fp8_amax_compute_algo: "most_recent"
fp8_margin: 0
fp8_interval: 1
fp8_amax_history_len: 1024
fp8_use_autocast_during_eval: false
fp8_override_linear_precision: [ false, false, false ]
fp8_opt_level: "O2"
