[project]
name = "agenticrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Carel van Niekerk", email = "vniekerk.carel@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.9.0",
    "hydra-core>=1.3.2",
    "pydantic>=2.11.7",
    "trl>=0.21.0",
    "wandb>=0.21.1",
]

[project.scripts]
agenticrl = "agenticrl.scripts:hello"

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"
